/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "RoadSideInfomation"
 */
#include "RoadSideInfomation.h"
#include "RoadSideInformation.h"

namespace roadsideinfomation {

RoadSideInformation::RoadSideInformation() {
}

void RoadSideInformation::free() {
	free_object(this, RoadSideInformation::TYPE, &RoadSideInformation::CONVERTER);
}

AsnType* RoadSideInformation::TYPE = RoadSideInfomation::getType(65537);
ASN_COMPOSITE(
	CompositeConverter,
	RoadSideInformation,
	{ 0 }
);

}
