/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "RoadSideInfomation"
 */

#ifndef ROADSIDEINFORMATION_H
#define ROADSIDEINFORMATION_H

#include "AsnRuntime.h"

using namespace asnrt;

namespace roadsideinfomation {

class RoadSideInformation {
public:

	RoadSideInformation();
	void free();

	DECLARE_TYPE();
	DECLARE_CONVERTER(CompositeConverter);
};

}

#endif /*ROADSIDEINFORMATION_H*/

