/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MessageFrame"
 */

#ifndef MESSAGEFRAME_H
#define MESSAGEFRAME_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif /*MESSAGEFRAME_H*/

