/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MapData"
 */

#ifndef MAPDATA_H
#define MAPDATA_H

#include "AsnRuntime.h"

using namespace asnrt;

namespace mapdata {

class MapData {
public:

	MapData();
	void free();

	DECLARE_TYPE();
	DECLARE_CONVERTER(CompositeConverter);
};

}

#endif /*MAPDATA_H*/

