/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DataElements"
 */
#include "DataElements.h"
#include "AntiLockBrakeStatus.h"

namespace dataelements {

AsnType* AntiLockBrakeStatus::TYPE = DataElements::getType(65537);
EnumeratedConverter<AntiLockBrakeStatus> AntiLockBrakeStatus::CONVERTER;

}
