/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "BasicSafetyMessage"
 */
#include "BasicSafetyMessage.h"
#include "BasicSafetyMessage.h"

namespace basicsafetymessage {

BasicSafetyMessage::BasicSafetyMessage() {
}

void BasicSafetyMessage::free() {
	free_object(this, BasicSafetyMessage::TYPE, &BasicSafetyMessage::CONVERTER);
}

AsnType* BasicSafetyMessage::TYPE = BasicSafetyMessage::getType(65537);
ASN_COMPOSITE(
	CompositeConverter,
	BasicSafetyMessage,
	{ 0 }
);

}
