/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "BasicSafetyMessage"
 */

#ifndef BASICSAFETYMESSAGE_H
#define BASICSAFETYMESSAGE_H

#include "AsnRuntime.h"

using namespace asnrt;

namespace basicsafetymessage {

class BasicSafetyMessage {
public:

	BasicSafetyMessage();
	void free();

	DECLARE_TYPE();
	DECLARE_CONVERTER(CompositeConverter);
};

}

#endif /*BASICSAFETYMESSAGE_H*/

