/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "RoadSideInfomation"
 */

#ifndef ROADSIDEINFOMATION_H
#define ROADSIDEINFOMATION_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif /*ROADSIDEINFOMATION_H*/

