/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "RoadsideSafetyMessage"
 */

#ifndef ROADSIDESAFETYMESSAGE_H
#define ROADSIDESAFETYMESSAGE_H

#include "AsnRuntime.h"

using namespace asnrt;

namespace roadsidesafetymessage {

class RoadsideSafetyMessage {
public:

	RoadsideSafetyMessage();
	void free();

	DECLARE_TYPE();
	DECLARE_CONVERTER(CompositeConverter);
};

}

#endif /*ROADSIDESAFETYMESSAGE_H*/

