/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "RoadsideSafetyMessage"
 */
#include "RoadsideSafetyMessage.h"
#include "RoadsideSafetyMessage.h"

namespace roadsidesafetymessage {

RoadsideSafetyMessage::RoadsideSafetyMessage() {
}

void RoadsideSafetyMessage::free() {
	free_object(this, RoadsideSafetyMessage::TYPE, &RoadsideSafetyMessage::CONVERTER);
}

AsnType* RoadsideSafetyMessage::TYPE = RoadsideSafetyMessage::getType(65537);
ASN_COMPOSITE(
	CompositeConverter,
	RoadsideSafetyMessage,
	{ 0 }
);

}
