/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "SPAT"
 */

#ifndef SPAT_H
#define SPAT_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif /*SPAT_H*/

