/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "MapData"
 */

#ifndef MAPDATA_H
#define MAPDATA_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif /*MAPDATA_H*/

