/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "RoadSideInformation"
 */

#ifndef ROADSIDEINFORMATION_H
#define ROADSIDEINFORMATION_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

#endif /*ROADSIDEINFORMATION_H*/

