/*
 * Generated by ASN.1 C++ Compiler (http://www.asnlab.org/)
 * From ASN.1 module "SPAT"
 */

#ifndef SPAT_H
#define SPAT_H

#include "AsnRuntime.h"

using namespace asnrt;

namespace spat {

class SPAT {
public:

	SPAT();
	void free();

	DECLARE_TYPE();
	DECLARE_CONVERTER(CompositeConverter);
};

}

#endif /*SPAT_H*/

