/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DataElements"
 */

#ifndef ALLOWEDMANEUVERS_H
#define ALLOWEDMANEUVERS_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif


#define	allowedManeuvers_maneuverStraightAllowed	0
#define	allowedManeuvers_maneuverLeftAllowed	1
#define	allowedManeuvers_maneuverRightAllowed	2
#define	allowedManeuvers_maneuverUTurnAllowed	3
#define	allowedManeuvers_maneuverLeftTurnOnRedAllowed	4
#define	allowedManeuvers_maneuverRightTurnOnRedAllowed	5
#define	allowedManeuvers_maneuverLaneChangeAllowed	6
#define	allowedManeuvers_maneuverNoStoppingAllowed	7
#define	allowedManeuvers_yieldAllwaysRequired	8
#define	allowedManeuvers_goWithHalt	9
#define	allowedManeuvers_caution	10
#define	allowedManeuvers_reserved1	11


extern PUBLIC const AsnType ALLOWEDMANEUVERS_TYPE;

extern int encode_AllowedManeuvers(AsnBuffer* buffer, Bits/*SIZE(12)*/* allowedManeuvers);
extern int decode_AllowedManeuvers(AsnBuffer* buffer, Bits/*SIZE(12)*/* allowedManeuvers);

#ifdef __cplusplus
}
#endif

#endif /*ALLOWEDMANEUVERS_H*/

