/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DataElements"
 */

#include "AntiLockBrakeStatus.h"

#ifdef __cplusplus
extern "C" {
#endif

const char* ANTILOCKBRAKESTATUS_TYPE_numNames_[] = { "unavailable", "off", "on", "engaged" };
const int ANTILOCKBRAKESTATUS_TYPE_enumValues_[] = { 0, 1, 2, 3 };
const AsnEnumerated ANTILOCKBRAKESTATUS_TYPE_enumerated_ = { ANTILOCKBRAKESTATUS_TYPE_numNames_, ANTILOCKBRAKESTATUS_TYPE_enumValues_, 4, 0, 2, 1, false, sizeof(enum AntiLockBrakeStatus) };

const AsnType ANTILOCKBRAKESTATUS_TYPE = { &ENUMERATED_CODEC, &ANTILOCKBRAKESTATUS_TYPE_enumerated_ };

int encode_AntiLockBrakeStatus(AsnBuffer* buffer, enum AntiLockBrakeStatus* antiLockBrakeStatus) {
	return encode_object(buffer, antiLockBrakeStatus, &ANTILOCKBRAKESTATUS_TYPE);
}

int decode_AntiLockBrakeStatus(AsnBuffer* buffer, enum AntiLockBrakeStatus* antiLockBrakeStatus) {
	return decode_object(buffer, antiLockBrakeStatus, &ANTILOCKBRAKESTATUS_TYPE);
}


#ifdef __cplusplus
}
#endif

