/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DataElements"
 */

#ifndef ANTILOCKBRAKESTATUS_H
#define ANTILOCKBRAKESTATUS_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif

enum AntiLockBrakeStatus {
   AntiLockBrakeStatus_unavailable = 0,
   AntiLockBrakeStatus_off = 1,
   AntiLockBrakeStatus_on = 2,
   AntiLockBrakeStatus_engaged = 3
};

extern PUBLIC const AsnType ANTILOCKBRAKESTATUS_TYPE;

extern int encode_AntiLockBrakeStatus(AsnBuffer* buffer, enum AntiLockBrakeStatus* antiLockBrakeStatus);
extern int decode_AntiLockBrakeStatus(AsnBuffer* buffer, enum AntiLockBrakeStatus* antiLockBrakeStatus);

#ifdef __cplusplus
}
#endif

#endif /*ANTILOCKBRAKESTATUS_H*/

