/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DataElements"
 */

#ifndef DATAELEMENTS_H
#define DATAELEMENTS_H

#include "asnrt.h"

#ifdef __cplusplus
extern "C" {
#endif

extern PUBLIC const AsnType ALERTTYPE_TYPE;

extern PUBLIC const AsnType ACCELERATION_TYPE;


#ifdef __cplusplus
}
#endif

#endif /*DATAELEMENTS_H*/

