/*
 * Generated by ASN.1 C Compiler (http://www.asnlab.org/)
 * From ASN.1 module "DataElements"
 */

#include "DataElements.h"

#ifdef __cplusplus
extern "C" {
#endif

// Memory Management

/**
 * Allocates a block (nitems * size) bytes and clears it to 0.
 * 
 * Override this function to provide your own allocation function.
 */
void* asn_alloc(size_t nitems, size_t size) {
	return calloc(nitems, size);
}

/**
 * Deallocates a memory block allocated by a previous call to asn_alloc().
 * 
 * Override this function to provide your own deallocation function.
 */
void asn_free(void* block) {
	if(block!=NULL) {
		free(block);
	}
}

/**
 * Copies a block of n bytes from src to dest.
 * 
 * Override this function to provide your own memory copy function.
 */
void* asn_memcpy(void* dest, const void* src, size_t n) {
	return memcpy(dest, src, n);
}

/**
 * Compares the first n bytes of the blocks s1 and s2 as unsigned chars.
 * 
 * Override this function to provide your own memory compare function.
 */
int asn_memcmp(const void* s1, const void* s2, size_t n) {
	return memcmp(s1, s2, n);
}

/**
 * Performs a binary search for the value key in a table (array) of nelem elements in memory.
 * Parameters:
 * 		key - The item to be searched for (the search key)
 *		base - The base (0th element) of the search table
 *		nelem - The number of entries in the table
 *		width - The number of bytes in each entry
 *		fcmp - A user-defined comparison routine that compares two items and returns a value based on the comparison
 * Return: The address of the first entry in the table that matches the search key on success; 0 (no match) on failure.
 * 
 * Override this function to provide your own bsearch function.
 */
void* asn_bsearch(const void* key, const void* base, size_t nelem, size_t width, int (*fcmp)(const void*, const void*)) {
	return bsearch(key, base, nelem, width, fcmp);
}

/* license */
char sn_key[] = {
	0x18, 0x29, 0xe7, 0x32, 0x41, 0x11, 0x2d, 0x84, 0x83, 0x92, 0x3e, 0xe2, 0x8f, 0x20, 0x5c, 0x40, 0x30, 0x60, 
	0xb4, 0x0d, 0x18, 0xbf, 0x17, 0xbb, 0x9f, 0x7a, 0x99, 0x62, 0xe8, 0x5d, 0xd1, 0xb1, 0x56, 0x45, 0xf8, 0xbb, 
	0x6a, 0x63, 0x02, 0x02, 0x87, 0x1b, 0xdc, 0x9d, 0x84, 0x5b, 0x5f, 0xa4
};
int sn_len = 48;

UINT_TYPE(ALERTTYPE_TYPE, 0U, 65535U, 2, true, true, 16, 2, 2, false);

INT_TYPE(ACCELERATION_TYPE, -2000, 2001, 2, true, true, 12, 2, 2, false);


#ifdef __cplusplus
}
#endif

